# Generated by Django 5.0.4 on 2024-04-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
