# Generated by Django 5.0.4 on 2024-04-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_prodution_email_production_production_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
    ]
