# Generated by Django 5.0.4 on 2024-04-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('production_studio', models.CharField(max_length=150, null=True)),
                ('production_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('coordinator_name', models.CharField(max_length=150, null=True)),
                ('coordinator_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('captain_name', models.CharField(max_length=150, null=True)),
                ('captain_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
            ],
        ),
    ]
