# Generated by Django 5.0.4 on 2024-04-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_runrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_contact', models.CharField(max_length=15)),
                ('location_address_1', models.CharField(max_length=100)),
                ('location_address_2', models.CharField(max_length=100, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=2)),
                ('location_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_address_1', models.CharField(max_length=100)),
                ('vendor_address_2', models.CharField(max_length=100, null=True)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=2)),
                ('vendor_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='runrequest',
            name='production_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
