# Generated by Django 5.0.4 on 2024-04-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_location_vendor_runrequest_production_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
