# Generated by Django 5.0.4 on 2024-04-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_vendor_vendor_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runrequest',
            name='assigned_driver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
