# Generated by Django 5.0.4 on 2024-04-13 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_runrequest_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='production_notes',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='production_title',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='run_details',
            field=models.TextField(max_length=500),
        ),
    ]
