# Generated by Django 5.0.4 on 2024-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_department_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='department_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
