# Generated by Django 5.0.4 on 2024-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_department_department_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='department_title',
        ),
    ]
