# Generated by Django 5.0.4 on 2024-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_jobtitle_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
