# Generated by Django 5.0.4 on 2024-04-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_alter_jobtitle_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='department',
            new_name='department_title',
        ),
    ]
