# Generated by Django 5.0.4 on 2024-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_rename_department_jobtitle_department_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='run_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
