# Generated by Django 5.0.4 on 2024-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_runrequest_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='purchase_order',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='vendor_invoice',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
