# Generated by Django 5.0.4 on 2024-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('driver_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('occupation_code', models.CharField(max_length=4, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('last_4', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('vehicle_type', models.CharField(max_length=150, null=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_unit_number', models.CharField(max_length=10, null=True)),
                ('internal_unit_number', models.CharField(max_length=20, null=True)),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('vehicle_notes', models.TextField(max_length=2000, null=True)),
                ('assigned_driver', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
